name: Format Check

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-19
          sudo ln -sf /usr/bin/clang-format-19 /usr/local/bin/clang-format
          clang-format --version

      - name: Run clang-format check
        run: |
          find . \
            -path "./test_build" -prune -o \
            -path "./build" -prune -o \
            -path "./.git" -prune -o \
            -type f \( -name "*.cpp" -o -name "*.h" \) -print \
            | xargs clang-format --dry-run --Werror -style=file